
export const productsData = [
    {
        "id": 1,
        "name": "Running Shoes",
        "description": "Lightweight and breathable shoes for long-distance running.",
        "size": 42,
        "color": "Blue",
        "price": 99.99,
        "delivery_time": "5 business days",
        "image_urls": ["/assets/tenis1.jpeg",
            "/assets/tenis2.jpeg",
            "/assets/tenis3.jpeg",
            "/assets/tenis4.jpeg",
            "/assets/tenis5.jpeg"],
        "category_id": 1,
        "collection_of_product_id": 1
    },
    {
        "id": 2,
        "name": "Basketball Shoes",
        "description": "High-performance shoes for maximum support on the court.",
        "size": 44,
        "color": "Red",
        "price": 120.00,
        "delivery_time": "3 business days",
        "image_urls": ["/assets/tenis1.jpeg",
            "/assets/tenis2.jpeg",
            "/assets/tenis3.jpeg",
            "/assets/tenis4.jpeg",
            "/assets/tenis5.jpeg"],
        "category_id": 2,
        "collection_of_product_id": 1
    },
    {
        "id": 3,
        "name": "Casual Sneakers",
        "description": "Comfortable sneakers for everyday use.",
        "size": 40,
        "color": "White",
        "price": 79.99,
        "delivery_time": "7 business days",
        "image_urls": ["/assets/tenis1.jpeg",
            "/assets/tenis2.jpeg",
            "/assets/tenis3.jpeg",
            "/assets/tenis4.jpeg",
            "/assets/tenis5.jpeg"],
        "category_id": 1,
        "collection_of_product_id": 1
    },
    {
        "id": 4,
        "name": "Tennis Shoes",
        "description": "Shoes designed for optimal grip and performance on tennis courts.",
        "size": 41,
        "color": "Green",
        "price": 89.99,
        "delivery_time": "4 business days",
        "image_urls": ["/assets/tenis1.jpeg",
            "/assets/tenis2.jpeg",
            "/assets/tenis3.jpeg",
            "/assets/tenis4.jpeg",
            "/assets/tenis5.jpeg"],
        "category_id": 2,
        "collection_of_product_id": 2
    },
    {
        "id": 5,
        "name": "Hiking Boots",
        "description": "Durable and waterproof boots for outdoor adventures.",
        "size": 43,
        "color": "Brown",
        "price": 150.00,
        "delivery_time": "6 business days",
        "image_urls": ["/assets/tenis1.jpeg",
            "/assets/tenis2.jpeg",
            "/assets/tenis3.jpeg",
            "/assets/tenis4.jpeg",
            "/assets/tenis5.jpeg"],
        "category_id": 1,
        "collection_of_product_id": 2
    }

]